module.exports = {
    ";d": ";d",
    "yamask": ";d",
    "colrful": "colrful",
    "minior": "colrful",
    "comepls": "come pls",
    "come_pls": "come pls",
    "drifblim": "come pls",
    "diagstep": "diagstep",
    "staryu": "diagstep",
    "direction": "direction",
    "inkay": "direction",
    "dragbl": "dragbl",
    "pokeball": "dragbl",
    "enby": "enby",
    "porygon": "enby",
    "pory": "enby",
    "flye": "flye",
    "mew": "flye",
    "folowal": "folo wal",
    "folo_wal": "folo wal",
    "wimpod": "folo wal",
    "fordor": "fordor",
    "klefki": "fordor",
    "klefkee": "fordor",
    "fridgd": "fridgd",
    "snorunt": "fridgd",
    "snowrunt": "fridgd",
    "glued": "glued",
    "magnemite": "glued",
    "goawaypls": "go away pls",
    "go_away_pls": "go away pls",
    "dwebble": "go away pls",
    "go": "go",
    "meltan": "go",
    "gone": "gone",
    "butterfree": "gone",
    "goooo": "goooo",
    "klink": "goooo",
    "gunne": "gunne",
    "gotgunne": "gunne",
    "got_gunne": "gunne",
    "mantine": "gunne",
    "haetflor": "haet flor",
    "haet_flor": "haet flor",
    "wailord": "haet flor",
    "haetskye": "haet skye",
    "haet_skye": "haet skye",
    "diglett": "haet skye",
    "hopovr": "hopovr",
    "spoink": "hopovr",
    "hotte": "hotte",
    "magcargo": "hotte",
    "icy": "icy",
    "bergmite": "icy",
    "icyyyy": "icyyyy",
    "avalugg": "icyyyy",
    "knightstep": "knightstep",
    "keldeo": "knightstep",
    "moar": "moar",
    "zubat": "moar",
    "munwalk": "munwalk",
    "mawile": "munwalk",
    "nedkee": "ned kee",
    "ned_kee": "ned kee",
    "blackdoor": "ned kee",
    "whitedoor": "ned kee",
    "pokestar": "ned kee",
    "door": "ned kee",
    "nodrag": "no drag",
    "no_drag": "no drag",
    "beldum": "no drag",
    "nogo": "no go",
    "no_go": "no go",
    "soodowoodo": "no go",
    "noswim": "no swim",
    "no_swim": "no swim",
    "dhelmise": "no swim",
    "noundo": "no undo",
    "no_undo": "no undo",
    "celebi": "no undo",
    "notranform": "notranform",
    "sad": "notranform",
    "nuek": "nuek",
    "electrode": "nuek",
    "voltorb": "nuek",
    "ouch": "ouch",
    "shedinja": "ouch",
    "paint": "paint",
    "smeargle": "paint",
    "poortoll": "poor toll",
    "poor_toll": "poor toll",
    "hoopa": "poor toll",
    "protecc": "protecc",
    "bronzong": "protecc",
    "qt": "qt",
    "eevee": "qt",
    "qt_hopovr": "qt_hopovr",
    "hopovr_qt": "qt_hopovr",
    "leafeon": "qt_hopovr",
    "qt_icy": "qt_icy",
    "icy_qt": "qt_icy",
    "glaceon": "qt_icy",
    "rave": "rave",
    "maractus": "rave",
    "rithere": "rithere",
    "nebby": "rithere",
    "cosmog": "rithere",
    "inthebag": "rithere",
    "rong": "rong",
    "nihilego": "rong",
    "sans": "sans",
    "duskull": "sans",
    "sant": "sant",
    "gotsant": "sant",
    "got_sant": "sant",
    "delibird": "sant",
    "sidestep": "sidestep",
    "krabby": "sidestep",
    "sing": "sing",
    "jigglypuff": "sing",
    "slep": "slep",
    "piloswine": "slep",
    "snacc": "snacc",
    "munchlax": "snacc",
    "split": "split",
    "dousion": "split",
    "spoop": "spoop",
    "haunter": "spoop",
    "stelth": "stelth",
    "kecleon": "stelth",
    "tall": "tall",
    "exeggutor": "tall",
    "alolanexeggutor": "tall",
    "alolan_exeggutor": "tall",
    "thingify": "thingify",
    "happy": "thingify",
    "thr": "thr",
    "abra": "thr",
    "torc": "torc",
    "litwick": "torc",
    "tranz": "tranz",
    "maril": "tranz",
    "utoo": "u too",
    "u_too": "u too",
    "charmander": "u too",
    "utres": "u tres",
    "u_tres": "u tres",
    "squirtle": "u tres",
    "u": "u",
    "bulbasaur": "u",
    "visitfren": "visit fren",
    "visit_fren": "visit fren",
    "spiritomb": "visit fren",
    "walk": "walk",
    "furret": "walk",
    "which": "which",
    "mismagius": "which",
    "whoa": "whoa",
    ":o": "whoa",
    "bonus": "whoa",
    "jirachi": "whoa",
    "wurd": "wurd",
    "unown": "wurd",
    "ditto": "wurd",
    "xwx": "xwx",
    "missingno": "xwx",
    "missingno.": "xwx",
    "yay": "yay",
    ":)": "yay",
    "win": "yay",
    "victin": "yay",
    "zip": "zip",
    "rotom": "zip",
}